<testsuites id="" name="" tests="1" failures="1" skipped="0" errors="0" time="65.11172999999998">
<testsuite name="e2e\employees\add-employee.spec.ts" timestamp="2025-04-01T22:08:12.516Z" hostname="chromium" tests="1" failures="1" skipped="0" time="60.069" errors="0">
<testcase name="[US02] Gestión de empleados | Agregar y validar empleados › Escenario 6 | Validar agregar un empleado con numeros y signos para NameInput y LastNameInput, y letras para IDIunput" classname="e2e\employees\add-employee.spec.ts" time="60.069">
<failure message="add-employee.spec.ts:185:9 Escenario 6 | Validar agregar un empleado con numeros y signos para NameInput y LastNameInput, y letras para IDIunput" type="FAILURE">
<![CDATA[  [chromium] › e2e\employees\add-employee.spec.ts:185:9 › [US02] Gestión de empleados | Agregar y validar empleados › Escenario 6 | Validar agregar un empleado con numeros y signos para NameInput y LastNameInput, y letras para IDIunput › Entonces se muestra un mensaje de error 

    Test timeout of 60000ms exceeded.

    Error: locator.waitFor: Test timeout of 60000ms exceeded.
    Call log:
      - waiting for locator('//span[text()=\'Required\']') to be visible


      205 |
      206 |         await test.step('Entonces se muestra un mensaje de error', async () => {
    > 207 |             await employeePage.requiredError.waitFor({ state: 'visible' });
          |                                              ^
      208 |             await employeePage.page.getByText('Employee Id already exists');
      209 |         });
      210 |
        at C:\Programacion\QA\Automation\Playwright-ts\Proyecto OrangeHRM\OrangeHRM-Demo\tests\e2e\employees\add-employee.spec.ts:207:46
        at C:\Programacion\QA\Automation\Playwright-ts\Proyecto OrangeHRM\OrangeHRM-Demo\tests\e2e\employees\add-employee.spec.ts:206:20
]]>
</failure>
</testcase>
</testsuite>
</testsuites>